name: tests
on:
  push:
    branches:
      - '**'

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git Private Repo
        run: |
          git config --global url."https://github.com/Netcracker/qubership-cql-driver.git".insteadOf "https://github.com/"	
      - name: Run Go tests
        run: go test ./...
